name: deploy
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 1) 전체 소스 SCP 전송
      - name: Copy repo to EC2
        uses: appleboy/scp-action@v0.1.1
        with:
          host:     ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key:      ${{ secrets.EC2_SSH_KEY }}
          source:   "."                                     # 저장소 루트
          target:   "/home/${{ secrets.EC2_USER }}/Arrange"

      # 2) 원격 배포 스크립트
      - name: Remote deploy commands
        uses: appleboy/ssh-action@v1
        with:
          host:     ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key:      ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            PROJECT_ROOT=/home/${{ secrets.EC2_USER }}/Arrange
            BACKEND_DIR=$PROJECT_ROOT/backend

            # 가상환경 준비(없으면 생성)
            if [ ! -d "$BACKEND_DIR/venv" ]; then
              python3 -m venv "$BACKEND_DIR/venv"
            fi
            source "$BACKEND_DIR/venv/bin/activate"

            # 의존 업데이트
            pip install --upgrade pip
            pip install -r "$BACKEND_DIR/requirements.txt"

            # 기존 uvicorn 프로세스 종료(있으면)
            pkill -f "uvicorn app.main:app" || true

            # 애플리케이션 실행
            cd "$BACKEND_DIR"
            nohup ./venv/bin/uvicorn app.main:app \
                  --host 0.0.0.0 --port 8000 --reload \
                  > ../uvicorn.out 2>&1 &


# name: Deploy to EC2

# on:
#   push:
#     branches: [ main ]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout
#       uses: actions/checkout@v2

#     - name: Set up Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: "3.10"

#     - name: Install deps
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r backend/requirements.txt

#     # ① 코드 업로드 (scp/rsync 전용 액션 사용 -- SSH 한 번)
#     - name: Copy backend to EC2
#       uses: appleboy/scp-action@v0.1.1
#       with:
#         host: ${{ secrets.EC2_HOST }}
#         username: ${{ secrets.EC2_USER }}          
#         key: ${{ secrets.EC2_SSH_KEY }}
#         source: "backend/"
#         target: "/home/${{ secrets.EC2_USER }}/myproject/backend"

#     # ② 원격 실행 (ssh-action -- 두 번째 SSH)
#     - name: Remote deploy commands
#       uses: appleboy/ssh-action@v0.1.2
#       with:
#         host: ${{ secrets.EC2_HOST }}
#         username: ${{ secrets.EC2_USER }}         
#         key: ${{ secrets.EC2_SSH_KEY }}
#         script: |
#           PROJECT_DIR=/home/${{ secrets.EC2_USER }}/myproject/backend
#           cd $PROJECT_DIR
#           # 이미 떠 있는 프로세스가 있다면 종료(선택)
#           pkill -f "uvicorn app.main:app" || true
#           # 새로 실행
#           nohup uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload > uvicorn.out 2>&1 &
