name: Deploy-FastAPI-Lambda

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'

env:
  BACKEND_DIR: backend
  LAMBDA_ARN: arn:aws:lambda:us-east-1:189588411513:function:Arrange

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Build Lambda zip
      run: |
        mkdir -p build
        if [ -f "$BACKEND_DIR/requirements.txt" ]; then
          pip install -r "$BACKEND_DIR/requirements.txt" -t build
        else
          pip install -r requirements.txt -t build
        fi
        rsync -av --exclude='__pycache__' "$BACKEND_DIR/" build/
        cd build && zip -r ../function.zip . && cd ..

    - uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region:            ${{ secrets.AWS_REGION }}

    - name: Update Lambda code
      run: |
        aws lambda update-function-code \
          --function-name $LAMBDA_ARN \
          --zip-file fileb://function.zip