name: Deploy-FastAPI-Lambda
on:
  push:
    branches: [main] # main에 머지될 때만

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) 코드 체크아웃
      - uses: actions/checkout@v3

      # 2) Python 세팅
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3) 패키징 ─ 소스 + 의존 모아 ZIP
      - name: Build Lambda zip
        run: |
          pip install -r requirements.txt -t package
          cp -R *.py package/
          cd package && zip -r ../function.zip . && cd ..

      # 4) AWS 자격증명 주입
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 5) Lambda 코드 업데이트
      - name: Update Lambda code
        run: |
          aws lambda update-function-code \
            --function-name  arn:aws:lambda:us-east-1:189588411513:function:Arrange \
            --zip-file       fileb://function.zip
